# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gRPC.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='gRPC.proto',
  package='url',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ngRPC.proto\x12\x03url\"\x18\n\nUrlRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"\x1b\n\x0bUrlResponse\x12\x0c\n\x04urls\x18\x01 \x01(\t\"7\n\x10\x43reateUrlRequest\x12\x0e\n\x06idUser\x18\x01 \x01(\x05\x12\x13\n\x0boriginalUrl\x18\x02 \x01(\t\" \n\x11\x43reateUrlResponse\x12\x0b\n\x03url\x18\x01 \x01(\t\"\x1c\n\x0eUrlInfoRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"\"\n\x0fUrlInfoResponse\x12\x0f\n\x07infoUrl\x18\x01 \x01(\t2\xb1\x01\n\nUrlService\x12.\n\tgetAllUrl\x12\x0f.url.UrlRequest\x1a\x10.url.UrlResponse\x12:\n\tcreateUrl\x12\x15.url.CreateUrlRequest\x1a\x16.url.CreateUrlResponse\x12\x37\n\ngetUrlInfo\x12\x13.url.UrlInfoRequest\x1a\x14.url.UrlInfoResponseb\x06proto3'
)




_URLREQUEST = _descriptor.Descriptor(
  name='UrlRequest',
  full_name='url.UrlRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='url.UrlRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=43,
)


_URLRESPONSE = _descriptor.Descriptor(
  name='UrlResponse',
  full_name='url.UrlResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='urls', full_name='url.UrlResponse.urls', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=72,
)


_CREATEURLREQUEST = _descriptor.Descriptor(
  name='CreateUrlRequest',
  full_name='url.CreateUrlRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='idUser', full_name='url.CreateUrlRequest.idUser', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='originalUrl', full_name='url.CreateUrlRequest.originalUrl', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=129,
)


_CREATEURLRESPONSE = _descriptor.Descriptor(
  name='CreateUrlResponse',
  full_name='url.CreateUrlResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='url.CreateUrlResponse.url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=131,
  serialized_end=163,
)


_URLINFOREQUEST = _descriptor.Descriptor(
  name='UrlInfoRequest',
  full_name='url.UrlInfoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='url.UrlInfoRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=165,
  serialized_end=193,
)


_URLINFORESPONSE = _descriptor.Descriptor(
  name='UrlInfoResponse',
  full_name='url.UrlInfoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='infoUrl', full_name='url.UrlInfoResponse.infoUrl', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=195,
  serialized_end=229,
)

DESCRIPTOR.message_types_by_name['UrlRequest'] = _URLREQUEST
DESCRIPTOR.message_types_by_name['UrlResponse'] = _URLRESPONSE
DESCRIPTOR.message_types_by_name['CreateUrlRequest'] = _CREATEURLREQUEST
DESCRIPTOR.message_types_by_name['CreateUrlResponse'] = _CREATEURLRESPONSE
DESCRIPTOR.message_types_by_name['UrlInfoRequest'] = _URLINFOREQUEST
DESCRIPTOR.message_types_by_name['UrlInfoResponse'] = _URLINFORESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UrlRequest = _reflection.GeneratedProtocolMessageType('UrlRequest', (_message.Message,), {
  'DESCRIPTOR' : _URLREQUEST,
  '__module__' : 'gRPC_pb2'
  # @@protoc_insertion_point(class_scope:url.UrlRequest)
  })
_sym_db.RegisterMessage(UrlRequest)

UrlResponse = _reflection.GeneratedProtocolMessageType('UrlResponse', (_message.Message,), {
  'DESCRIPTOR' : _URLRESPONSE,
  '__module__' : 'gRPC_pb2'
  # @@protoc_insertion_point(class_scope:url.UrlResponse)
  })
_sym_db.RegisterMessage(UrlResponse)

CreateUrlRequest = _reflection.GeneratedProtocolMessageType('CreateUrlRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEURLREQUEST,
  '__module__' : 'gRPC_pb2'
  # @@protoc_insertion_point(class_scope:url.CreateUrlRequest)
  })
_sym_db.RegisterMessage(CreateUrlRequest)

CreateUrlResponse = _reflection.GeneratedProtocolMessageType('CreateUrlResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREATEURLRESPONSE,
  '__module__' : 'gRPC_pb2'
  # @@protoc_insertion_point(class_scope:url.CreateUrlResponse)
  })
_sym_db.RegisterMessage(CreateUrlResponse)

UrlInfoRequest = _reflection.GeneratedProtocolMessageType('UrlInfoRequest', (_message.Message,), {
  'DESCRIPTOR' : _URLINFOREQUEST,
  '__module__' : 'gRPC_pb2'
  # @@protoc_insertion_point(class_scope:url.UrlInfoRequest)
  })
_sym_db.RegisterMessage(UrlInfoRequest)

UrlInfoResponse = _reflection.GeneratedProtocolMessageType('UrlInfoResponse', (_message.Message,), {
  'DESCRIPTOR' : _URLINFORESPONSE,
  '__module__' : 'gRPC_pb2'
  # @@protoc_insertion_point(class_scope:url.UrlInfoResponse)
  })
_sym_db.RegisterMessage(UrlInfoResponse)



_URLSERVICE = _descriptor.ServiceDescriptor(
  name='UrlService',
  full_name='url.UrlService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=232,
  serialized_end=409,
  methods=[
  _descriptor.MethodDescriptor(
    name='getAllUrl',
    full_name='url.UrlService.getAllUrl',
    index=0,
    containing_service=None,
    input_type=_URLREQUEST,
    output_type=_URLRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='createUrl',
    full_name='url.UrlService.createUrl',
    index=1,
    containing_service=None,
    input_type=_CREATEURLREQUEST,
    output_type=_CREATEURLRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='getUrlInfo',
    full_name='url.UrlService.getUrlInfo',
    index=2,
    containing_service=None,
    input_type=_URLINFOREQUEST,
    output_type=_URLINFORESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_URLSERVICE)

DESCRIPTOR.services_by_name['UrlService'] = _URLSERVICE

# @@protoc_insertion_point(module_scope)
